# Generated by Django 4.2.16 on 2024-09-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='xx_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
